name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy -- --base-href=https://menuexpert.app --cname=menuexpert.app
